#!/bin/bash

if [ "$#" = "0" ]
then
	echo "Error: Usage $0 <search term>" 1>&2
	exit
fi

for i in popeyes mcdonalds white-castle
do
	echo "$i"
	echo "-------"

	grep -i $1 $i.csv

	if [ "$?" != "0" ]
	then
		echo "\"$1\" is not available at $i"
	fi

	echo
done

